src/SummitDemo/Models/Buchung.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FlugDemo.Models
{

    public class Buchung
    {
        public int BuchungId { get; set; }
        public DateTime Datum { get; set; }

        public int FlugId { get; set; }
        public Flug Flug { get; set; }

        public int PassagierId { get; set; }

        // public Passagier Passagier { get; set; }
    }
}

src/SummitDemo/Models/Flug.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Threading.Tasks;

namespace FlugDemo.Models
{
    public class Flug
    {
        public int Id { get; set; }

        [MaxLength(30)]
        [Required]
        public string AblugOrt { get; set; }

        [MaxLength(30)]
        [Required]
        public string ZielOrt { get; set; }

        public DateTime Datum { get; set; }

        [MaxLength(30)]
        [Required]
        public string FlugNr { get; set; }

        public List<Buchung> Buchungen { get; set; } = new List<Buchung>();
    }
}

src/SummitDemo/Controllers/FlugController.cs
using FlugDemo.Data;
using FlugDemo.Models;
using Microsoft.AspNet.Mvc;
using SummitDemo.ActionResults;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SummitDemo.Controllers
{
    [Route("api/[controller]")]
    public class FlugController: Controller
    {
        IFlugRepository repo;

        public FlugController(IFlugRepository repo)
        {
            this.repo = repo;
        }

        [HttpGet]
        public List<Flug> GetAll() {
            return this.repo.FindAll();
        }

        [HttpGet("{id}")]
        public Flug GetById(int id) {
            return this.repo.FindById(id);
        }

        [HttpGet("byRoute")]
        public List<Flug> GetByRoute(string von, string nach) {
            return this.repo.FindByRoute(von, nach);
        }

        [HttpPost]
        public IActionResult Post([FromBody] Flug flug) {
            this.repo.Save(flug);
            // Ok()
            // HttpNotFound

            return CreatedAtAction("GetById", new { id = flug.Id  }, flug);
            // return new AcceptedActionResult();
        }
    }
}

src/SummitDemo/Controllers/HomeController.cs
using FlugDemo.Data;
using Microsoft.AspNet.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SummitDemo.Controllers
{
    public class HomeController: Controller
    {
        // private IFlugRepository repo = new FlugEfRepository();
        //private IFlugRepository repo = new FlugDemoRepository();

        private IFlugRepository repo;

        public HomeController(IFlugRepository repo)
        {
            this.repo = repo;
        }

        // /Home/Index
        public ActionResult Index() {
            var all = this.repo.FindAll();
            return View("List", all); 
        }

        // /Home/Detail?id=1
        // /Home/Detail/1
        public ActionResult Detail(int id) {
            var flug = this.repo.FindById(id);
            return View("Detail", flug);
        }

    }
}

src/SummitDemo/Views/Home/Detail.cshtml
@model FlugDemo.Models.Flug
@{
    ViewBag.Title = "Detail";
}

<table class="table table-striped">
    <tr>
        <td>Id: </td>
        <td>@Model.Id</td>
    </tr>
    <tr>
        <td>Von: </td>
        <td>@Model.AblugOrt</td>
    </tr>
    <tr>
        <td>Nach: </td>
        <td>@Model.ZielOrt</td>
    </tr>
    <tr>
        <td>Datum: </td>
        <td>@Model.Datum</td>
    </tr>
</table>

src/SummitDemo/Views/Home/List.cshtml
@model List<FlugDemo.Models.Flug>

@{
    ViewBag.Title = "Flüge";
}

<!-- Twitter Bootstrap -->
<table class="table table-striped">
    @foreach (var flug in Model)
    {
        <tr>
            <td>@flug.Id</td>
            <td>@flug.Datum</td>
            <td>@flug.AblugOrt</td>
            <td>@flug.ZielOrt</td>
            <td><a asp-action="Detail" 
                   asp-controller="Home"
                   asp-route-id="@flug.Id">Detail</a></td>
            
        </tr>
    }
</table>

@section infos {
    (c) Manfred Steyer, 2016
}

src/SummitDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - Demo</title>

    
    <link rel="stylesheet" href="~/css/styles.css" />
    <style>
        body {
            margin-top:40px;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-controller="Home" asp-action="Index" class="navbar-brand">Demo</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-controller="Flug" asp-action="Index">Flüge</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <h1>@ViewBag.Title</h1>
        @RenderBody()
    </div>
    <div>
        <hr />
            @RenderSection("infos", required: false)
        <hr />
    </div>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("scripts", required: false)
</body>
</html>